import { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  en: {
    navFeatures: 'Features',
    navHowItWorks: 'How it Works',
    navStories: 'Stories',
    navFaq: 'FAQ',
    signIn: 'Sign In',
    openDashboard: 'Open Dashboard',
    phoneLabel: 'Phone',
    dashboard: 'Dashboard',
    payments: 'Payments',
    paymentHistory: 'Payment History',
    totalPayments: 'Total Payments',
    upcomingPayments: 'Upcoming Payments',
    recordPayment: 'Record Payment',
    newMember: 'New Member',
    addMember: 'Add Member',
    memberRole: 'SHG Leader',
    heroBadge: 'Trusted by NGOs and rural finance leaders',
    heroTitle: 'Empowering Rural Women Through Digital Self Help Group Management',
    heroSubtitle: 'Manage members, savings, loans, meetings, reports, and analytics in one secure platform tailored for rural institutions and community networks.',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    aboutTitle: 'A premium operating system for community finance',
    aboutSubtitle: 'Built to support SHGs, cooperatives, NGOs, and government partners with calm, secure, and modern workflows.',
    aiSectionTitle: 'AI Copilot for field teams',
    aiSectionSubtitle: 'Let assistive intelligence summarize meetings, flag risk, and suggest next steps in plain language.',
    aiCard1Title: 'Meeting Summaries',
    aiCard1Text: 'Turn meeting notes into concise action items for leaders and members.',
    aiCard2Title: 'Risk Detection',
    aiCard2Text: 'Spot delayed repayments and unusual savings patterns before they become issues.',
    aiCard3Title: 'Multilingual Notes',
    aiCard3Text: 'Capture updates in the field and translate them into shared reports instantly.',
    dashboardTitle: 'Welcome back, Sushila',
    overviewBadge: 'Operations Overview',
    quickActionsTitle: 'Quick Actions',
    aiPanelTitle: 'AI Assistant',
    aiPanelText: 'Ask for a summary, next best action, or repayment reminder for your current SHG.',
    actionMember: 'Add Member',
    actionDeposit: 'Record Deposit',
    actionLoan: 'Approve Loan',
    actionMeeting: 'Schedule Meeting',
    actionPrompt: 'Generate guidance',
    membersBadge: 'Member Directory',
    membersTitle: 'Community members at a glance',
    searchMember: 'Search member',
    memberColumn: 'Member',
    joinedColumn: 'Joined',
    savingsColumn: 'Savings',
    loanColumn: 'Loan',
    attendanceColumn: 'Attendance',
    statusColumn: 'Status',
    savingsBadge: 'Savings Overview',
    savingsTitle: 'Monthly collection rising steadily',
    monthBalance: 'Current month balance',
    transactionHistory: 'Transaction History',
    depositRecords: 'Deposit Records',
    exportLabel: 'Export',
    dateColumn: 'Date',
    amountColumn: 'Amount',
    loanBadge: 'Loan Pipeline',
    loanTitle: 'Repayment progress remains healthy',
    openRequests: 'Open Requests',
    recoveryRate: 'Recovery Rate',
    repaymentTracker: 'Repayment Tracker',
    meetingsBadge: 'Meetings',
    meetingsTitle: 'Calendar, attendance, agenda, and minutes in one place',
    upcomingMeeting: 'Upcoming Meeting',
    monthlyReview: 'Monthly Review • 20 Jul 2026',
    agendaText: 'Agenda: loan approvals, savings review, and field updates.',
    attendanceLabel: 'Attendance',
    attendanceValue: '28 present • 2 absent',
    attendanceText: 'Attendance recorded in three minutes using mobile check-in.',
    photoUploads: 'Photo Uploads',
    photoText: 'Meeting photos and field notes can be attached as supporting evidence for audits and reporting.',
    authTrust: 'Secure digital trust',
    authTitle: 'SakhiSetu authentication',
    authSubtitle: 'Role-based access, protected sessions, and a premium experience designed for field teams and leadership alike.',
    authMobile: 'Mobile-friendly signing',
    authMobileText: 'Optimized for low-connectivity environments and compact screens.',
    emailLabel: 'Email',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    forgotPassword: 'Forgot password?',
    createAccount: 'Create account',
    aboutEyebrow: 'About SakhiSetu',
    howItWorksEyebrow: 'How It Works',
    successEyebrow: 'Success Stories',
    successTitle: 'Trusted by leaders who value impact',
    successSubtitle: 'Real stories from community-led organizations that scale with dignity.',
    galleryEyebrow: 'Gallery',
    galleryTitle: 'A platform that reflects real community life',
    gallerySubtitle: 'Every experience is designed to feel human, calm, and credible.',
    faqEyebrow: 'Frequently Asked Questions',
    faqTitle: 'Everything you need to know',
    faqSubtitle: 'Designed to simplify adoption for both technical and non-technical teams.',
    faqQuestionOne: 'Can SakhiSetu work offline?',
    faqAnswerOne: 'Yes, field officers can record activity locally and sync data when connectivity resumes.',
    faqQuestionTwo: 'Is the platform secure?',
    faqAnswerTwo: 'Role-based access, encrypted sessions, and audit logs are built in for trust and compliance.',
    footerText: 'Premium self help group management for modern rural finance.',
    totalMembers: 'Total Members',
    totalSavings: 'Total Savings',
    activeLoans: 'Active Loans',
    monthlyCollection: 'Monthly Collection',
    upcomingMeetings: 'Upcoming Meetings',
    recentActivity: 'Recent Activity',
    viewAll: 'View all',
    syncLabel: 'Sync',
    newMember: 'New Member',
    stepOneTitle: 'Create your SHG profile',
    stepOneText: 'Onboard your group, members, and governance rules in a few guided steps.',
    stepTwoTitle: 'Digitize collections',
    stepTwoText: 'Capture savings, dues, and meeting outcomes from the field in real time.',
    stepThreeTitle: 'Make decisions faster',
    stepThreeText: 'Use dashboards and reports to support lending, planning, and compliance.',
    statsSHGs: 'SHGs Digitized',
    statsMembers: 'Rural Members',
    statsRecovery: 'Loan Recovery',
    statsTime: 'Avg. Time Saved',
    featureMemberTitle: 'Unified Member Management',
    featureMemberText: 'Track profiles, attendance, savings, and loan health from one view.',
    featureSavingsTitle: 'Secure Savings Workflow',
    featureSavingsText: 'Automate deposits, weekly collections, and real-time transaction history.',
    featureLoansTitle: 'Smart Loan Operations',
    featureLoansText: 'Approve requests, structure EMI plans, and monitor repayment progress.',
    featureAnalyticsTitle: 'Insightful Analytics',
    featureAnalyticsText: 'Generate growth and financial health reports with confidence.',
    governmentTitle: 'Built for transparency, reporting, and long-term trust',
    governmentSubtitle: 'Support grant tracking, financial inclusion initiatives, and compliance reporting with a modular system that scales from one village to many districts.',
    authLoginTitle: 'Welcome back',
    authLoginSubtitle: 'Sign in to continue your rural finance operations.',
    authRegisterTitle: 'Create your organization',
    authRegisterSubtitle: 'Start digitizing your SHG network with security and clarity.',
    authForgotTitle: 'Reset your password',
    authForgotSubtitle: 'We will send a secure recovery link to your email.',
    authVerifyTitle: 'Verify your email',
    authVerifySubtitle: 'Confirm your inbox before continuing.',
    authOtpTitle: 'Enter verification code',
    authOtpSubtitle: 'Use the code sent to your phone for quick access.',
    authButtonLogin: 'Sign In',
    authButtonRegister: 'Create Account',
    authButtonForgot: 'Send Recovery Link',
    authButtonVerify: 'Verify Email',
    authButtonOtp: 'Verify Code',
    authNavCreate: 'Create account',
    authNavForgot: 'Forgot password?',
    paymentStatus: 'Status',
    paymentMethod: 'Method',
    paymentAmount: 'Amount',
    paymentDate: 'Date',
    paymentSuccess: 'Paid',
    paymentPending: 'Pending'
  },
  hi: {
    navFeatures: 'विशेषताएँ',
    navHowItWorks: 'यह कैसे काम करता है',
    navStories: 'सफलता की कहानियाँ',
    navFaq: 'अक्सर पूछे जाने वाले प्रश्न',
    signIn: 'साइन इन',
    openDashboard: 'डैशबोर्ड खोलें',
    heroBadge: 'NGO और ग्रामीण वित्त नेतृत्व द्वारा भरोसा किया गया',
    heroTitle: 'डिजिटल ऐप से अपनी स्वयं सहायता समूह को आसान तरीके से चलाएं',
    heroSubtitle: 'सदस्यों, बचत, ऋण, बैठकों और रिपोर्ट्स सब एक ही जगह, आसान और सुरक्षित तरीके से।',
    getStarted: 'शुरू करें',
    learnMore: 'और जानें',
    aboutTitle: 'समुदाय के पैसे और काम के लिए आसान और भरोसेमंद प्लेटफ़ॉर्म',
    aboutSubtitle: 'SHG, सहकारी संस्थाओं, NGO और सरकारी टीमों के लिए सरल, सुरक्षित और तेज़ काम।',
    aiSectionTitle: 'मैदानी टीमों के लिए AI सहायक',
    aiSectionSubtitle: 'बैठक का सार, जोखिम और अगली कार्रवाई आसान भाषा में तुरंत समझ में आए।',
    aiCard1Title: 'बैठक सारांश',
    aiCard1Text: 'बैठक नोट्स को नेताओं और सदस्यों के लिए संक्षिप्त कार्रवाई बिंदुओं में बदलें।',
    aiCard2Title: 'जोखिम पहचान',
    aiCard2Text: 'देरी से हुई अदायगी और असामान्य बचत पैटर्न को समस्या बनने से पहले पहचानें।',
    aiCard3Title: 'बहुभाषी नोट्स',
    aiCard3Text: 'फील्ड अपडेट को रिकॉर्ड करें और उन्हें तुरंत साझा रिपोर्ट में अनुवादित करें।',
    dashboardTitle: 'वापस स्वागत है, सुषीला',
    overviewBadge: 'ऑपरेशंस अवलोकन',
    quickActionsTitle: 'तेज़ काम',
    aiPanelTitle: 'AI सहायक',
    aiPanelText: 'अपने SHG के लिए सारांश, अगली कार्रवाई या किस्त की याद दिलाने के लिए पूछें।',
    actionMember: 'सदस्य जोड़ें',
    actionDeposit: 'जमा दर्ज करें',
    actionLoan: 'ऋण स्वीकृत करें',
    actionMeeting: 'बैठक शेड्यूल करें',
    actionPrompt: 'मार्गदर्शन बनाएं',
    membersBadge: 'सदस्य निर्देशिका',
    membersTitle: 'एक ही नजर में सारे सदस्य',
    searchMember: 'सदस्य खोजें',
    addMember: 'सदस्य जोड़ें',
    memberColumn: 'सदस्य',
    joinedColumn: 'शामिल हुए',
    savingsColumn: 'बचत',
    loanColumn: 'ऋण',
    attendanceColumn: 'उपस्थिति',
    statusColumn: 'स्थिति',
    savingsBadge: 'बचत अवलोकन',
    savingsTitle: 'मासिक बचत लगातार बढ़ रही है',
    monthBalance: 'वर्तमान माह शेष',
    transactionHistory: 'लेनदेन इतिहास',
    depositRecords: 'जमा रिकॉर्ड',
    exportLabel: 'निर्यात',
    dateColumn: 'तिथि',
    amountColumn: 'राशि',
    loanBadge: 'ऋण पाइपलाइन',
    loanTitle: 'ऋण की वसूली ठीक चल रही है',
    openRequests: 'खुले अनुरोध',
    recoveryRate: 'वसूली दर',
    repaymentTracker: 'किस्त ट्रैकर',
    meetingsBadge: 'बैठकें',
    meetingsTitle: 'कैलेंडर, हाज़िरी, agenda और नोट्स एक ही जगह',
    upcomingMeeting: 'आगामी बैठक',
    monthlyReview: 'मासिक समीक्षा • 20 Jul 2026',
    agendaText: 'कार्यसूची: ऋण अनुमोदन, बचत समीक्षा और फील्ड अपडेट।',
    attendanceLabel: 'उपस्थिति',
    attendanceValue: '28 उपस्थित • 2 अनुपस्थित',
    attendanceText: 'मोबाइल चेक-इन के जरिए तीन मिनट में उपस्थिति दर्ज की गई।',
    photoUploads: 'फोटो अपलोड',
    photoText: 'बैठक की तस्वीरें और फील्ड नोट्स ऑडिट और रिपोर्टिंग के लिए प्रमाण के रूप में अटैच किए जा सकते हैं।',
    authTrust: 'सुरक्षित और भरोसेमंद डिजिटल अनुभव',
    authTitle: 'SakhiSetu में साइन इन करें',
    authSubtitle: 'सरल और सुरक्षित तरीके से अपने SHG के काम को आगे बढ़ाएँ।',
    authMobile: 'मोबाइल-अनुकूल साइन-इन',
    authMobileText: 'कम-कनेक्टिविटी वातावरण और छोटे स्क्रीन के लिए अनुकूलित।',
    emailLabel: 'ईमेल',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'पासवर्ड',
    passwordPlaceholder: 'अपना पासवर्ड दर्ज करें',
    forgotPassword: 'पासवर्ड भूल गए?',
    createAccount: 'खाता बनाएं',
    aboutEyebrow: 'SakhiSetu के बारे में',
    howItWorksEyebrow: 'यह कैसे काम करता है',
    successEyebrow: 'सफलता की कहानियाँ',
    successTitle: 'उन नेताओं द्वारा भरोसा किया गया जो प्रभाव को महत्व देते हैं',
    successSubtitle: 'समुदाय-नेतृत्व वाली संस्थाओं की वास्तविक कहानियाँ जो गरिमा के साथ फैलती हैं।',
    galleryEyebrow: 'गैलरी',
    galleryTitle: 'एक ऐसा प्लेटफ़ॉर्म जो वास्तविक समुदाय जीवन को दर्शाता है',
    gallerySubtitle: 'हर अनुभव मानव, शांत और विश्वसनीय महसूस करने के लिए डिज़ाइन किया गया है।',
    faqEyebrow: 'अक्सर पूछे जाने वाले प्रश्न',
    faqTitle: 'आपको जो कुछ जानना है',
    faqSubtitle: 'तकनीकी और गैर-तकनीकी दोनों टीमों के लिए गोद लेने को सरल बनाने के लिए डिज़ाइन किया गया है।',
    faqQuestionOne: 'क्या SakhiSetu ऑफलाइन काम कर सकता है?',
    faqAnswerOne: 'हां, फील्ड ऑफिसर स्थानीय रूप से गतिविधि रिकॉर्ड कर सकते हैं और कनेक्टिविटी लौटने पर डेटा सिंक कर सकते हैं।',
    faqQuestionTwo: 'क्या प्लेटफ़ॉर्म सुरक्षित है?',
    faqAnswerTwo: 'विश्वास और अनुपालन के लिए भूमिका-आधारित पहुंच, एन्क्रिप्टेड सत्र और ऑडिट लॉग शामिल हैं।',
    footerText: 'आधुनिक ग्रामीण वित्त के लिए प्रीमियम स्वयं सहायता समूह प्रबंधन।',
    totalMembers: 'कुल सदस्य',
    totalSavings: 'कुल बचत',
    activeLoans: 'सक्रिय ऋण',
    monthlyCollection: 'मासिक संग्रह',
    upcomingMeetings: 'आगामी बैठकें',
    recentActivity: 'हाल की गतिविधि',
    viewAll: 'सभी देखें',
    syncLabel: 'सिंक',
    newMember: 'नया सदस्य',
    memberRole: 'SHG नेता',
    stepOneTitle: 'अपना SHG प्रोफ़ाइल बनाएं',
    stepOneText: 'कुछ मार्गदर्शित चरणों में अपनी समूह, सदस्यों और शासन नियमों को जोड़ें।',
    stepTwoTitle: 'संग्रह डिजिटाइज़ करें',
    stepTwoText: 'फील्ड से वास्तविक समय में बचत, देय राशि और बैठक परिणाम कैप्चर करें।',
    stepThreeTitle: 'तेज़ी से निर्णय लें',
    stepThreeText: 'ऋण, योजना और अनुपालन का समर्थन करने के लिए डैशबोर्ड और रिपोर्ट का उपयोग करें।',
    statsSHGs: 'डिजिटाइज़ किए गए SHG',
    statsMembers: 'ग्रामीण सदस्य',
    statsRecovery: 'ऋण वसूली',
    statsTime: 'औसत समय बचाया',
    featureMemberTitle: 'एकीकृत सदस्य प्रबंधन',
    featureMemberText: 'एक हीビュー में प्रोफ़ाइल, उपस्थिति, बचत और ऋण स्वास्थ्य ट्रैक करें।',
    featureSavingsTitle: 'सुरक्षित बचत कार्यप्रवाह',
    featureSavingsText: 'जमा, साप्ताहिक संग्रह और रीयल-टाइम लेनदेन इतिहास को स्वचालित करें।',
    featureLoansTitle: 'स्मार्ट ऋण संचालन',
    featureLoansText: 'अनुरोधों को स्वीकृत करें, EMI योजनाएँ तैयार करें और अदायगी प्रगति की निगरानी करें।',
    featureAnalyticsTitle: 'जानकारीपूर्ण एनालिटिक्स',
    featureAnalyticsText: 'विश्वास के साथ वृद्धि और वित्तीय स्वास्थ्य रिपोर्ट उत्पन्न करें।',
    governmentTitle: 'पारदर्शिता, रिपोर्टिंग और दीर्घकालिक विश्वास के लिए बनाया गया',
    governmentSubtitle: 'ग्रामों से कई जिलों तक फैलने वाली एक मॉड्यूलर प्रणाली के साथ अनुदान ट्रैकिंग, वित्तीय समावेशन और अनुपालन रिपोर्टिंग का समर्थन करें।',
    authLoginTitle: 'वापस स्वागत है',
    authLoginSubtitle: 'अपने ग्रामीण वित्त संचालन को जारी रखने के लिए साइन इन करें।',
    authRegisterTitle: 'अपनी संगठन बनाएं',
    authRegisterSubtitle: 'सुरक्षा और स्पष्टता के साथ अपने SHG नेटवर्क को डिजिटाइज़ करना शुरू करें।',
    authForgotTitle: 'अपना पासवर्ड रीसेट करें',
    authForgotSubtitle: 'हम आपके ईमेल पर एक सुरक्षित रिकवरी लिंक भेजेंगे।',
    authVerifyTitle: 'अपना ईमेल सत्यापित करें',
    authVerifySubtitle: 'जारी रखने से पहले अपने इनबॉक्स की पुष्टि करें।',
    authOtpTitle: 'सत्यापन कोड दर्ज करें',
    authOtpSubtitle: 'त्वरित पहुंच के लिए अपने फोन पर भेजा गया कोड का उपयोग करें।',
    authButtonLogin: 'साइन इन',
    authButtonRegister: 'खाता बनाएं',
    authButtonForgot: 'रिकवरी लिंक भेजें',
    authButtonVerify: 'ईमेल सत्यापित करें',
    authButtonOtp: 'कोड सत्यापित करें',
    authNavCreate: 'खाता बनाएं',
    authNavForgot: 'पासवर्ड भूल गए?'
  },
  te: {
    navFeatures: 'విశేషాలు',
    navHowItWorks: 'ఇది ఎలా పని చేస్తుంది',
    navStories: 'విజయం కథలు',
    navFaq: 'తరచుగా అడిగే ప్రశ్నలు',
    signIn: 'సైన్ ఇన్',
    openDashboard: 'డాష్బోర్డ్ను తెరవండి',
    heroBadge: 'NGOలు మరియు పల్లెపని నాయకుల విశ్వాసం',
    heroTitle: 'డిజిటల్ సెల్ఫ్ హెల్ప్ గ్రూప్ మేనేజ్మెంట్‌తో గ్రామీణ మహిళలను శక్తివంతం చేయడం',
    heroSubtitle: 'సభ్యులు, పొదుపు, రుణాలు, సమావేశాలు, నివేదికలు మరియు అనలిటిక్స్‌ను ఒక సురక్షిత వేదికపై ఒకే చోట నిర్వహించండి.',
    getStarted: 'ప్రారంభించండి',
    learnMore: 'మరింత తెలుసుకోండి',
    aboutTitle: 'సంఘం ఆర్థికానికి ఒక ప్రీమియం ఆపరేటింగ్ సిస్టమ్',
    aboutSubtitle: 'SHGలు, సహకార సంస్థలు, NGOలు మరియు ప్రభుత్వ భాగస్వాముల కోసం ప్రశాంతమైన, సురక్షితమైన మరియు ఆధునిక వర్క్ఫ్లోలను రూపొందించండి.',
    aiSectionTitle: 'ఫీల్డ్ టీమ్‌లకు AI సహాయకుడు',
    aiSectionSubtitle: 'సహాయక బুদ্ধిమత్త్వం సమావేశాల సంక్షిప్తాలను, ప్రమాద సూచనలను మరియు తదుపరి చర్యలను సులభమైన భాషలో సూచిస్తుంది.',
    aiCard1Title: 'సమావేశ సారాంశాలు',
    aiCard1Text: 'సమావేశ వ్రాతలను నాయకులు మరియు సభ్యుల కోసం సంక్షిప్త చర్య అంశాలుగా మార్చండి.',
    aiCard2Title: 'రిస్క్ గుర్తింపు',
    aiCard2Text: 'సమస్యలు కడుపులోకి వెళ్లకముందే ఆలస్యం అయిన చెల్లింపులు మరియు అసాధారణ పొదుపులను గుర్తించండి.',
    aiCard3Title: 'బహుభాషా నోట్లు',
    aiCard3Text: 'ఫీల్డ్ అప్డేట్‌లను రికార్డ్ చేసి తక్షణమే పంచుకున్న నివేదికలుగా అనువదించండి.',
    dashboardTitle: 'మళ్లీ స్వాగతం, సుషీల',
    overviewBadge: 'ఆపరేషన్స్ అవలోకనం',
    quickActionsTitle: 'త్వరిత చర్యలు',
    aiPanelTitle: 'AI సహాయకుడు',
    aiPanelText: 'మీ ప్రస్తుత SHG కోసం సంగ్రహం, తదుపరి ఉత్తమ చర్య లేదా చెల్లింపు రిమైండర్ కోసం అడగండి.',
    actionMember: 'సభ్యుడిని ઉમరించండి',
    actionDeposit: 'డిపాజిట్ రికార్డ్ చేయండి',
    actionLoan: 'రవాణా రుణం ఆమోదించండి',
    actionMeeting: 'సమావేశాన్ని షెడ్యూల్ చేయండి',
    actionPrompt: 'మార్గదర్శకత్వం జనరేట్ చేయండి',
    membersBadge: 'సభ్యుల డైరెక్టరీ',
    membersTitle: 'ఒక చూపులో కమ్యూనిటీ సభ్యులు',
    searchMember: 'సభ్యుడిని వెతకండి',
    addMember: 'సభ్యుడిని జోడించండి',
    memberColumn: 'సభ్యుడు',
    joinedColumn: 'చేరిన తేది',
    savingsColumn: 'పొదుపు',
    loanColumn: 'రుణం',
    attendanceColumn: 'హాజరు',
    statusColumn: 'స్థితి',
    savingsBadge: 'పొదుపు అవలోకనం',
    savingsTitle: 'నెలసరి సేకరణ స్థిరంగా పెరుగుతోంది',
    monthBalance: 'ప్రస్తుత నెల బ్యాలెన్స్',
    transactionHistory: 'లావాదేవీ చరిత్ర',
    depositRecords: 'డిపాజిట్ రికార్డులు',
    exportLabel: 'ఎగుమతి',
    dateColumn: 'తేదీ',
    amountColumn: 'మొత్తం',
    loanBadge: 'రుణం పైప్లైన్',
    loanTitle: 'చెల్లింపు పురోగతి ఆరోగ్యంగా ఉంది',
    openRequests: 'ఖোলা అభ్యర్థనలు',
    recoveryRate: 'వాపసు రేటు',
    repaymentTracker: 'చెల్లింపు ట్రాకర్',
    meetingsBadge: 'సమావేశాలు',
    meetingsTitle: 'ఒకే ప్రదేశంలో క్యాలెండర్, హాజరు, కార్యసూత్రం మరియు నిమిషాలు',
    upcomingMeeting: 'రాబోయే సమావేశం',
    monthlyReview: 'మాసిక సమీక్ష • 20 Jul 2026',
    agendaText: 'కార్యసూచిక: రుణ ఆమోదాలు, పొదుపు సమీక్ష మరియు ఫీల్డ్ అప్డేట్లు.',
    attendanceLabel: 'హాజరు',
    attendanceValue: '28 హాజరయ్యారు • 2 గైర్హాజరులు',
    attendanceText: 'మొబైల్ చెక్-ఇన్ ద్వారా మూడు నిమిషాల్లో హాజరు రికార్డ్ చేయబడింది.',
    photoUploads: 'ఫోటో అప్‌లోడ్‌లు',
    photoText: 'సమావేశ ఫోటోలు మరియు ఫీల్డ్ నోట్లు ఆడిట్ మరియు రిపోర్టింగ్ కోసం సమర్పణలుగా జోడించవచ్చు.',
    authTrust: 'సురక్షిత డిజిటల్ విశ్వాసం',
    authTitle: 'SakhiSetu ప్రామాణీకరణ',
    authSubtitle: 'రోల్-ఆధారిత ప్రాప్యత, రక్షిత సెషన్లు మరియు ఫీల్డ్ టీమ్‌లు మరియు నాయకుల కోసం ఒక ప్రీమియం అనుభవం.',
    authMobile: 'మొబైల్-ఫ్రెండ్లీ సైన్-ఇన్',
    authMobileText: 'తక్కువ-కనెక్షన్ వాతావరణాలు మరియు కుంచించు స్క్రీన్‌లకు అనుకూలంగా ఉంటుంది.',
    emailLabel: 'ఇమెయిల్',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'పాస్‌వర్డ్',
    passwordPlaceholder: 'మీ పాస్‌వర్డ్‌ను నమోదు చేయండి',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    createAccount: 'ఖాతాను సృష్టించండి',
    aboutEyebrow: 'SakhiSetu గురించి',
    howItWorksEyebrow: 'ఇది ఎలా పని చేస్తుంది',
    successEyebrow: 'విజయం కథలు',
    successTitle: 'ప్రభావాన్ని విలువైనదిగా భావించే నాయకులచే విశ్వసించబడింది',
    successSubtitle: 'సామాజిక-నాయకత్వ సంస్థల వాస్తవ కథలు, గౌరవంతో విస్తరిస్తాయి.',
    galleryEyebrow: 'గ్యాలరీ',
    galleryTitle: 'వాస్తవ సముదాయ జీవితాన్ని ప్రతిబింబించే ఒక ప్లాట్ఫారమ్',
    gallerySubtitle: 'ప్రతి అనుభవం మానవీయంగా, శాంతిగా మరియు విశ్వసనీయంగా అనిపించేలా రూపొందించబడింది.',
    faqEyebrow: 'తరచుగా అడిగే ప్రశ్నలు',
    faqTitle: 'మీకు తెలుసుకోవలసిన ప్రతి విషయం',
    faqSubtitle: 'టెక్నికల్ మరియు నాన్-టెక్నికల్ టిమ్స్ రెండింటికీ తీసుకోవడాన్ని సులభతరం చేయడానికి రూపొందించబడింది.',
    faqQuestionOne: 'SakhiSetu ఆఫ్‌లైన్ పనిచేయగలదా?',
    faqAnswerOne: 'అవును, ఫీల్డ్ ఆఫీసర్లు స్థానికంగా చర్యలను రికార్డ్ చేయగలరు మరియు కనెక్టివిటీ తిరిగి వచ్చినప్పుడు డేటాను సింక్ చేయగలరు.',
    faqQuestionTwo: 'ప్లాట్ఫారమ్ సురక్షితమా?',
    faqAnswerTwo: 'విశ్వాసం మరియు అనుగుణమైన విధుల కోసం రోల్-ఆధారిత ప్రాప్యత, ఎన్క్రిప్ట్ చేయబడిన సెషన్లు మరియు ఆడిట్ లాగ్లు చేర్చబడ్డాయి.',
    footerText: 'ఆధునిక గ్రామీణ ఆర్థికకు ప్రీమియం స్వీయ సహాయ సమూహ నిర్వహణ।',
    totalMembers: 'మొత్తం సభ్యులు',
    totalSavings: 'మొత్తం పొదుపు',
    activeLoans: 'సక్రియ రుణాలు',
    monthlyCollection: 'మాసిక సేకరణ',
    upcomingMeetings: 'రాబోయే సమావేశాలు',
    recentActivity: 'ఇటీవలి చర్య',
    viewAll: 'అన్ని చూడండి',
    syncLabel: 'సింక్',
    newMember: 'కొత్త సభ్యుడు',
    memberRole: 'SHG నేత',
    stepOneTitle: 'మీ SHG ప్రొఫైల్‌ను సృష్టించండి',
    stepOneText: 'కొన్ని మార్గదర్శకమైన దశల్లో మీ సమూహం, సభ్యులు మరియు పాలన నియమాలను నమోదు చేయండి.',
    stepTwoTitle: 'సేకరణలను డిజిటైజ్ చేయండి',
    stepTwoText: 'ఫీల్డ్ నుండి నిజ సమయంలో పొదుపు, బకాయి మరియు సమావేశ ఫలితాలను రికార్డ్ చేయండి.',
    stepThreeTitle: 'త్వరగా నిర్ణయాలు తీసుకోండి',
    stepThreeText: 'రుణాలు, ప్రణాళిక మరియు అనుగుణతకు మద్దతు ఇవ్వడానికి డాష్‌బోర్డ్లు మరియు నివేదికలను ఉపయోగించండి.',
    statsSHGs: 'డిజిటైజ్ చేసిన SHGలు',
    statsMembers: 'గ్రామీణ సభ్యులు',
    statsRecovery: 'రుణ వసూలు',
    statsTime: 'సగటు సమయం ఆదా',
    featureMemberTitle: 'ఏకీకృత సభ్యుల నిర్వహణ',
    featureMemberText: 'ఒకే వీక్షణలో ప్రొఫైల్స్, హాజరు, పొదుపు మరియు రుణ ఆరోగ్యాన్ని ట్రాక్ చేయండి.',
    featureSavingsTitle: 'సురక్షిత పొదుపు వర్క్ఫ్లో',
    featureSavingsText: 'డిపాజిట్లు, వారం వారం సేకరణలు మరియు రియల్-టైమ్ లావాదేవీ చరిత్రలను ఆటోమేటిక్ చేయండి.',
    featureLoansTitle: 'స్మార్ట్ రుణ ఆపరేషన్స్',
    featureLoansText: 'అభ్యర్థనలను ఆమోదించండి, EMI ప్లాన్లను నిర్మించండి మరియు చెల్లింపు పురోగతిని పర్యవేక్షించండి.',
    featureAnalyticsTitle: 'సూచనాత్మక అనలిటిక్స్',
    featureAnalyticsText: 'నమ్మకంగా వృద్ధి మరియు ఆర్థిక ఆరోగ్య నివేదికలను రూపొందించండి.',
    governmentTitle: 'పారదర్శకత, నివేదిక మరియు దీర్ఘకాలిక విశ్వాసం కోసం రూపొందించబడింది',
    governmentSubtitle: 'గ్రామం నుండి అనేక జిల్లాల వరకు విస్తరించే మాడ్యులర్ సిస్టమ్‌తో గ్రాంట్ ట్రాకింగ్, ఆర్థిక సమావেশ మరియు అనుగుణత నివేదికలను మద్దతు ఇవ్వండి.',
    authLoginTitle: 'మళ్లీ స్వాగతం',
    authLoginSubtitle: 'మీ గ్రామీణ ఆర్థిక కార్యకలాపాలను కొనసాగించడానికి సైన్ ఇన్ చేయండి.',
    authRegisterTitle: 'మీ సంస్థను సృష్టించండి',
    authRegisterSubtitle: 'సురక్షితత మరియు స్పష్టతతో మీ SHG నెట్‌వర్క్‌ను డిజిటైజ్ చేయడం ప్రారంభించండి.',
    authForgotTitle: 'మీ పాస్‌వర్డ్‌ను రీసెట్ చేయండి',
    authForgotSubtitle: 'మీ ఇమెయిల్‌కు ఒక సురక్షిత తిరిగి పొందే లింక్‌ను పంపుతాము.',
    authVerifyTitle: 'మీ ఇమెయిల్‌ను ధృవీకరించండి',
    authVerifySubtitle: 'కొనసాగడానికి ముందు మీ ఇన్‌బాక్స్‌ను నిర్ధారించండి.',
    authOtpTitle: 'ధృవీకరణ కోడ్‌ను నమోదు చేయండి',
    authOtpSubtitle: 'త్వరిత ప్రాప్యత కోసం మీ ఫోన్‌కు పంపించిన కోడ్‌ను ఉపయోగించండి.',
    authButtonLogin: 'సైన్ ఇన్',
    authButtonRegister: 'ఖాతాను సృష్టించండి',
    authButtonForgot: 'రీకవరీ లింక్ పంపండి',
    authButtonVerify: 'ఇమెయిల్ ధృవీకరించండి',
    authButtonOtp: 'కోడ్ ధృవీకరించండి',
    authNavCreate: 'ఖాతాను సృష్టించండి',
    authNavForgot: 'పాస్‌వర్డ్ మర్చిపోయారా?'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] || translations.en[key] || key
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
